import { BeneficiaryRecord, DistrictAuthorityRecord, FPSShop } from '../types/pds';

export const SEED_DISTRICT_AUTHORITIES: DistrictAuthorityRecord[] = [
  {
    id: 'DIST-BLR-URBAN',
    districtName: 'Bengaluru Urban',
    officerName: 'Dr. H. Rajeshwari, IAS',
    loginId: 'GOV-KAR-DSO-8841',
    passcode: 'KAR-PDS-2026',
    tier: 'dso',
    division: 'Bengaluru Division',
    officeAddress: 'Deputy Commissioner Complex, K.G. Road, Bengaluru 560009',
    email: 'dso.bangalore@ahara.kar.nic.in',
    phone: '+91 80 2221 4450',
    fpsCount: 1420,
    beneficiaryCount: 1842000,
    bufferGodown: 'Yeshwanthpur Central Buffer Godown (Hub 1)',
    activeDispatchesCount: 4,
  },
  {
    id: 'DIST-MYSURU',
    districtName: 'Mysuru',
    officerName: 'Sri. K. Ramesh Rao, KAS',
    loginId: 'GOV-KAR-DSO-5701',
    passcode: 'MYS-PDS-2026',
    tier: 'dso',
    division: 'Mysuru Division',
    officeAddress: 'Zilla Panchayat Office, Krishnaraja Boulevard, Chamarajapuram, Mysuru 570005',
    email: 'dso.mysuru@ahara.kar.nic.in',
    phone: '+91 821 242 2100',
    fpsCount: 1084,
    beneficiaryCount: 1240000,
    bufferGodown: 'Mysuru South APMC Buffer Godown',
    activeDispatchesCount: 2,
  },
  {
    id: 'DIST-BELAGAVI',
    districtName: 'Belagavi',
    officerName: 'Smt. Sunita Patil, KAS',
    loginId: 'GOV-KAR-DSO-5901',
    passcode: 'BEL-PDS-2026',
    tier: 'dso',
    division: 'Belagavi Division',
    officeAddress: 'DC Office Compound, Court Road, Belagavi 590001',
    email: 'dso.belagavi@ahara.kar.nic.in',
    phone: '+91 831 240 7200',
    fpsCount: 1560,
    beneficiaryCount: 1650000,
    bufferGodown: 'Belagavi Industrial Area Central Godown',
    activeDispatchesCount: 3,
  },
  {
    id: 'DIST-KALABURAGI',
    districtName: 'Kalaburagi',
    officerName: 'Sri. Mallikarjun G., KAS',
    loginId: 'GOV-KAR-DSO-5851',
    passcode: 'KLB-PDS-2026',
    tier: 'dso',
    division: 'Kalaburagi Division (Kalyana Karnataka)',
    officeAddress: 'Mini Vidhana Soudha, Main Road, Kalaburagi 585102',
    email: 'dso.kalaburagi@ahara.kar.nic.in',
    phone: '+91 8472 278 600',
    fpsCount: 980,
    beneficiaryCount: 980000,
    bufferGodown: 'Kalaburagi APMC Buffer Godown',
    activeDispatchesCount: 2,
  },
  {
    id: 'DIST-DAKSHINA-KANNADA',
    districtName: 'Dakshina Kannada',
    officerName: 'Sri. Prashanth Kumar, KAS',
    loginId: 'GOV-KAR-DSO-5751',
    passcode: 'DKN-PDS-2026',
    tier: 'dso',
    division: 'Mysuru / Coastal Division',
    officeAddress: 'DC Office Complex, Bunder, Mangaluru 575001',
    email: 'dso.mangaluru@ahara.kar.nic.in',
    phone: '+91 824 222 0580',
    fpsCount: 640,
    beneficiaryCount: 720000,
    bufferGodown: 'Baikampady Harbor Buffer Godown',
    activeDispatchesCount: 1,
  },
];

export const SEED_FPS_DEALERS: FPSShop[] = [
  {
    id: 'KA-BLR-FPS-104',
    shopNumber: 'Shop #104',
    name: 'Shri Renuka Prasanna Fair Price Depot',
    dealerName: 'Manjunath K. Gowda',
    phoneNumber: '+91 94481 22910',
    ward: 'Ward 42 (Malleshwaram)',
    taluk: 'Bengaluru North',
    district: 'Bengaluru Urban',
    address: '15th Cross, Sampige Road, Malleshwaram, Bengaluru 560003',
    coordinates: { lat: 13.0031, lng: 77.5701, x: 28, y: 35 },
    beneficiaryCount: 1420,
    readinessStatus: 'Verified',
    distributionStarted: false,
    stock: [
      { id: 'raw_rice', name: 'Raw Rice', nameKn: 'ಅಕ್ಕಿ', currentKg: 1250, allocatedKg: 8500, monthlyDemandKg: 7800, unit: 'kg', unitPriceRs: 0 },
      { id: 'wheat', name: 'Wheat', nameKn: 'ಗೋಧಿ', currentKg: 420, allocatedKg: 2100, monthlyDemandKg: 1950, unit: 'kg', unitPriceRs: 2 },
      { id: 'sugar', name: 'Sugar', nameKn: 'ಸಕ್ಕರೆ', currentKg: 95, allocatedKg: 1420, monthlyDemandKg: 1400, unit: 'kg', unitPriceRs: 13.5 },
      { id: 'toor_dal', name: 'Toor Dal', nameKn: 'ತೊಗರಿ ಬೇಳೆ', currentKg: 110, allocatedKg: 1420, monthlyDemandKg: 1400, unit: 'kg', unitPriceRs: 25 },
      { id: 'oil', name: 'Sunflower Oil', nameKn: 'ಎಣ್ಣೆ', currentKg: 80, allocatedKg: 1420, monthlyDemandKg: 1400, unit: 'L', unitPriceRs: 25 },
    ],
    lastMonthLeftover: { rawRiceKg: 185, wheatKg: 45, sugarKg: 12, dalKg: 18, reportedAt: '2026-08-31' },
  },
  {
    id: 'KA-BLR-FPS-105',
    shopNumber: 'Shop #105',
    name: 'Gayatri Mahila Seva Co-op PDS',
    dealerName: 'Savithri Devi',
    phoneNumber: '+91 98452 77109',
    ward: 'Ward 42 (Malleshwaram)',
    taluk: 'Bengaluru North',
    district: 'Bengaluru Urban',
    address: '8th Main, Pipeline Road, Malleshwaram, Bengaluru 560003',
    coordinates: { lat: 13.0084, lng: 77.5672, x: 22, y: 28 },
    beneficiaryCount: 1180,
    readinessStatus: 'Verified',
    distributionStarted: true,
    distributionStartedAt: '2026-09-23 09:30 AM',
    stock: [
      { id: 'raw_rice', name: 'Raw Rice', nameKn: 'ಅಕ್ಕಿ', currentKg: 6400, allocatedKg: 6500, monthlyDemandKg: 6200, unit: 'kg', unitPriceRs: 0 },
      { id: 'wheat', name: 'Wheat', nameKn: 'ಗೋಧಿ', currentKg: 1800, allocatedKg: 1850, monthlyDemandKg: 1750, unit: 'kg', unitPriceRs: 2 },
      { id: 'sugar', name: 'Sugar', nameKn: 'ಸಕ್ಕರೆ', currentKg: 1120, allocatedKg: 1180, monthlyDemandKg: 1150, unit: 'kg', unitPriceRs: 13.5 },
      { id: 'toor_dal', name: 'Toor Dal', nameKn: 'ತೊಗರಿ ಬೇಳೆ', currentKg: 1100, allocatedKg: 1180, monthlyDemandKg: 1150, unit: 'kg', unitPriceRs: 25 },
      { id: 'oil', name: 'Sunflower Oil', nameKn: 'ಎಣ್ಣೆ', currentKg: 1150, allocatedKg: 1180, monthlyDemandKg: 1150, unit: 'L', unitPriceRs: 25 },
    ],
    lastMonthLeftover: { rawRiceKg: 90, wheatKg: 20, sugarKg: 8, dalKg: 5, reportedAt: '2026-08-31' },
  },
  {
    id: 'KA-MYS-FPS-202',
    shopNumber: 'Shop #202',
    name: 'Chamundeshwari Souharda Sahakari PDS',
    dealerName: 'M. Puttaswamy',
    phoneNumber: '+91 94482 11094',
    ward: 'Ward 14 (Saraswathipuram)',
    taluk: 'Mysuru City',
    district: 'Mysuru',
    address: 'Near 5th Main Bus Stand, Saraswathipuram, Mysuru 570009',
    coordinates: { lat: 12.3021, lng: 76.6342, x: 40, y: 50 },
    beneficiaryCount: 1320,
    readinessStatus: 'Verified',
    distributionStarted: false,
    stock: [
      { id: 'raw_rice', name: 'Raw Rice', nameKn: 'ಅಕ್ಕಿ', currentKg: 4200, allocatedKg: 8000, monthlyDemandKg: 7800, unit: 'kg', unitPriceRs: 0 },
      { id: 'wheat', name: 'Wheat', nameKn: 'ಗೋಧಿ', currentKg: 1100, allocatedKg: 2000, monthlyDemandKg: 1900, unit: 'kg', unitPriceRs: 2 },
      { id: 'sugar', name: 'Sugar', nameKn: 'ಸಕ್ಕರೆ', currentKg: 750, allocatedKg: 1300, monthlyDemandKg: 1250, unit: 'kg', unitPriceRs: 13.5 },
      { id: 'toor_dal', name: 'Toor Dal', nameKn: 'ತೊಗರಿ ಬೇಳೆ', currentKg: 820, allocatedKg: 1300, monthlyDemandKg: 1250, unit: 'kg', unitPriceRs: 25 },
      { id: 'oil', name: 'Sunflower Oil', nameKn: 'ಎಣ್ಣೆ', currentKg: 800, allocatedKg: 1300, monthlyDemandKg: 1250, unit: 'L', unitPriceRs: 25 },
    ],
    lastMonthLeftover: { rawRiceKg: 120, wheatKg: 35, sugarKg: 10, dalKg: 12, reportedAt: '2026-08-31' },
  },
  {
    id: 'KA-MYS-FPS-208',
    shopNumber: 'Shop #208',
    name: 'Kaveri Consumers Co-op Society',
    dealerName: 'Geetha N.',
    phoneNumber: '+91 98451 44521',
    ward: 'Ward 08 (Gokulam)',
    taluk: 'Mysuru City',
    district: 'Mysuru',
    address: '3rd Stage, 6th Cross, Gokulam, Mysuru 570002',
    coordinates: { lat: 12.3245, lng: 76.6210, x: 42, y: 48 },
    beneficiaryCount: 960,
    readinessStatus: 'Verified',
    distributionStarted: true,
    distributionStartedAt: '2026-09-23 08:45 AM',
    stock: [
      { id: 'raw_rice', name: 'Raw Rice', nameKn: 'ಅಕ್ಕಿ', currentKg: 5200, allocatedKg: 5800, monthlyDemandKg: 5600, unit: 'kg', unitPriceRs: 0 },
      { id: 'wheat', name: 'Wheat', nameKn: 'ಗೋಧಿ', currentKg: 1400, allocatedKg: 1500, monthlyDemandKg: 1450, unit: 'kg', unitPriceRs: 2 },
      { id: 'sugar', name: 'Sugar', nameKn: 'ಸಕ್ಕರೆ', currentKg: 910, allocatedKg: 960, monthlyDemandKg: 940, unit: 'kg', unitPriceRs: 13.5 },
      { id: 'toor_dal', name: 'Toor Dal', nameKn: 'ತೊಗರಿ ಬೇಳೆ', currentKg: 920, allocatedKg: 960, monthlyDemandKg: 940, unit: 'kg', unitPriceRs: 25 },
      { id: 'oil', name: 'Sunflower Oil', nameKn: 'ಎಣ್ಣೆ', currentKg: 930, allocatedKg: 960, monthlyDemandKg: 940, unit: 'L', unitPriceRs: 25 },
    ],
    lastMonthLeftover: { rawRiceKg: 85, wheatKg: 18, sugarKg: 6, dalKg: 9, reportedAt: '2026-08-31' },
  },
  {
    id: 'KA-BEL-FPS-305',
    shopNumber: 'Shop #305',
    name: 'Rani Chennamma Raitha Seva Kendra',
    dealerName: 'Mahadev S. Kulkarni',
    phoneNumber: '+91 94490 88210',
    ward: 'Ward 22 (Tilakwadi)',
    taluk: 'Belagavi City',
    district: 'Belagavi',
    address: 'Congress Road, Near 3rd Railway Gate, Tilakwadi, Belagavi 590006',
    coordinates: { lat: 15.8497, lng: 74.5089, x: 25, y: 30 },
    beneficiaryCount: 1580,
    readinessStatus: 'Verified',
    distributionStarted: false,
    stock: [
      { id: 'raw_rice', name: 'Raw Rice', nameKn: 'ಅಕ್ಕಿ', currentKg: 3100, allocatedKg: 9500, monthlyDemandKg: 9200, unit: 'kg', unitPriceRs: 0 },
      { id: 'wheat', name: 'Wheat', nameKn: 'ಗೋಧಿ', currentKg: 2800, allocatedKg: 4000, monthlyDemandKg: 3800, unit: 'kg', unitPriceRs: 2 },
      { id: 'sugar', name: 'Sugar', nameKn: 'ಸಕ್ಕರೆ', currentKg: 800, allocatedKg: 1580, monthlyDemandKg: 1500, unit: 'kg', unitPriceRs: 13.5 },
      { id: 'toor_dal', name: 'Toor Dal', nameKn: 'ತೊಗರಿ ಬೇಳೆ', currentKg: 780, allocatedKg: 1580, monthlyDemandKg: 1500, unit: 'kg', unitPriceRs: 25 },
      { id: 'oil', name: 'Sunflower Oil', nameKn: 'ಎಣ್ಣೆ', currentKg: 790, allocatedKg: 1580, monthlyDemandKg: 1500, unit: 'L', unitPriceRs: 25 },
    ],
    lastMonthLeftover: { rawRiceKg: 210, wheatKg: 90, sugarKg: 15, dalKg: 20, reportedAt: '2026-08-31' },
  },
  {
    id: 'KA-BEL-FPS-312',
    shopNumber: 'Shop #312',
    name: 'Kittur Co-operative Society',
    dealerName: 'Anand B. Desai',
    phoneNumber: '+91 98801 33412',
    ward: 'Ward 10 (Camp)',
    taluk: 'Belagavi City',
    district: 'Belagavi',
    address: 'Club Road, Camp, Belagavi 590001',
    coordinates: { lat: 15.8582, lng: 74.5120, x: 27, y: 28 },
    beneficiaryCount: 1220,
    readinessStatus: 'Verified',
    distributionStarted: true,
    distributionStartedAt: '2026-09-22 11:00 AM',
    stock: [
      { id: 'raw_rice', name: 'Raw Rice', nameKn: 'ಅಕ್ಕಿ', currentKg: 6800, allocatedKg: 7200, monthlyDemandKg: 7000, unit: 'kg', unitPriceRs: 0 },
      { id: 'wheat', name: 'Wheat', nameKn: 'ಗೋಧಿ', currentKg: 2900, allocatedKg: 3100, monthlyDemandKg: 3000, unit: 'kg', unitPriceRs: 2 },
      { id: 'sugar', name: 'Sugar', nameKn: 'ಸಕ್ಕರೆ', currentKg: 1180, allocatedKg: 1220, monthlyDemandKg: 1200, unit: 'kg', unitPriceRs: 13.5 },
      { id: 'toor_dal', name: 'Toor Dal', nameKn: 'ತೊಗರಿ ಬೇಳೆ', currentKg: 1190, allocatedKg: 1220, monthlyDemandKg: 1200, unit: 'kg', unitPriceRs: 25 },
      { id: 'oil', name: 'Sunflower Oil', nameKn: 'ಎಣ್ಣೆ', currentKg: 1200, allocatedKg: 1220, monthlyDemandKg: 1200, unit: 'L', unitPriceRs: 25 },
    ],
    lastMonthLeftover: { rawRiceKg: 110, wheatKg: 40, sugarKg: 12, dalKg: 14, reportedAt: '2026-08-31' },
  },
  {
    id: 'KA-KLB-FPS-401',
    shopNumber: 'Shop #401',
    name: 'Sharana Basaveshwara Annapurna Kendra',
    dealerName: 'Basalingappa Biradar',
    phoneNumber: '+91 97412 55901',
    ward: 'Ward 18 (Super Market)',
    taluk: 'Kalaburagi City',
    district: 'Kalaburagi',
    address: 'Main Road, Old City Market, Kalaburagi 585101',
    coordinates: { lat: 17.3297, lng: 76.8343, x: 60, y: 20 },
    beneficiaryCount: 1680,
    readinessStatus: 'Verified',
    distributionStarted: false,
    stock: [
      { id: 'raw_rice', name: 'Raw Rice', nameKn: 'ಅಕ್ಕಿ', currentKg: 2200, allocatedKg: 10200, monthlyDemandKg: 9900, unit: 'kg', unitPriceRs: 0 },
      { id: 'wheat', name: 'Wheat', nameKn: 'ಗೋಧಿ', currentKg: 850, allocatedKg: 2500, monthlyDemandKg: 2400, unit: 'kg', unitPriceRs: 2 },
      { id: 'sugar', name: 'Sugar', nameKn: 'ಸಕ್ಕರೆ', currentKg: 350, allocatedKg: 1680, monthlyDemandKg: 1620, unit: 'kg', unitPriceRs: 13.5 },
      { id: 'toor_dal', name: 'Toor Dal', nameKn: 'ತೊಗರಿ ಬೇಳೆ', currentKg: 420, allocatedKg: 1680, monthlyDemandKg: 1620, unit: 'kg', unitPriceRs: 25 },
      { id: 'oil', name: 'Sunflower Oil', nameKn: 'ಎಣ್ಣೆ', currentKg: 390, allocatedKg: 1680, monthlyDemandKg: 1620, unit: 'L', unitPriceRs: 25 },
    ],
    lastMonthLeftover: { rawRiceKg: 310, wheatKg: 60, sugarKg: 18, dalKg: 24, reportedAt: '2026-08-31' },
  },
  {
    id: 'KA-DKN-FPS-510',
    shopNumber: 'Shop #510',
    name: 'Kudroli Gokarnanatha Seva Trust PDS',
    dealerName: 'Ganesh Shetty',
    phoneNumber: '+91 94483 77122',
    ward: 'Ward 32 (Hampankatta)',
    taluk: 'Mangaluru',
    district: 'Dakshina Kannada',
    address: 'K.S. Rao Road, Hampankatta, Mangaluru 575001',
    coordinates: { lat: 12.8698, lng: 74.8430, x: 15, y: 70 },
    beneficiaryCount: 1140,
    readinessStatus: 'Verified',
    distributionStarted: false,
    stock: [
      { id: 'raw_rice', name: 'Raw Rice (Boiled/Raw)', nameKn: 'ಕುಚಲಕ್ಕಿ / ಅಕ್ಕಿ', currentKg: 4500, allocatedKg: 7000, monthlyDemandKg: 6800, unit: 'kg', unitPriceRs: 0 },
      { id: 'wheat', name: 'Wheat', nameKn: 'ಗೋಧಿ', currentKg: 950, allocatedKg: 1700, monthlyDemandKg: 1600, unit: 'kg', unitPriceRs: 2 },
      { id: 'sugar', name: 'Sugar', nameKn: 'ಸಕ್ಕರೆ', currentKg: 850, allocatedKg: 1140, monthlyDemandKg: 1100, unit: 'kg', unitPriceRs: 13.5 },
      { id: 'toor_dal', name: 'Toor Dal', nameKn: 'ತೊಗರಿ ಬೇಳೆ', currentKg: 880, allocatedKg: 1140, monthlyDemandKg: 1100, unit: 'kg', unitPriceRs: 25 },
      { id: 'oil', name: 'Sunflower Oil', nameKn: 'ಎಣ್ಣೆ', currentKg: 820, allocatedKg: 1140, monthlyDemandKg: 1100, unit: 'L', unitPriceRs: 25 },
    ],
    lastMonthLeftover: { rawRiceKg: 140, wheatKg: 25, sugarKg: 11, dalKg: 15, reportedAt: '2026-08-31' },
  },
];

export const SEED_BENEFICIARIES: BeneficiaryRecord[] = [
  // 1. Bengaluru Urban - Shop #104
  {
    id: 'BEN-BLR-001',
    rationCardNumber: 'KA-04-PHH-882941',
    cardType: 'PHH (BPL)',
    headOfHousehold: 'Basavaraj Patil',
    headOfHouseholdKn: 'ಬಸವರಾಜ ಪಾಟೀಲ',
    districtId: 'DIST-BLR-URBAN',
    district: 'Bengaluru Urban',
    taluk: 'Bengaluru North',
    ward: 'Ward 42 (Malleshwaram)',
    assignedFpsId: 'KA-BLR-FPS-104',
    assignedFpsName: 'Shri Renuka Prasanna Fair Price Depot (Shop #104)',
    assignedFpsAddress: '15th Cross, Sampige Road, Malleshwaram, Bengaluru 560003',
    phoneNumber: '+91 98450 12837',
    totalQuotaKg: 26,
    currentCycleCollected: false,
    activeTokenNumber: 'TKN-2026-09-0412',
    bookedSlot: { date: 'Day 12 (Thursday)', timeShift: '08:00 AM - 10:00 AM', bookedAt: '2026-09-22 18:00' },
    loginPin: '882941',
    aadhaarLast4: '4912',
    members: [
      { name: 'Basavaraj Patil', relation: 'Head', age: 48, gender: 'Male', aadhaarMasked: 'XXXX-XXXX-4912' },
      { name: 'Sumangala Patil', relation: 'Spouse', age: 44, gender: 'Female', aadhaarMasked: 'XXXX-XXXX-8104' },
      { name: 'Chethan Patil', relation: 'Son', age: 21, gender: 'Male', aadhaarMasked: 'XXXX-XXXX-3381' },
      { name: 'Ananya Patil', relation: 'Daughter', age: 17, gender: 'Female', aadhaarMasked: 'XXXX-XXXX-9920' },
    ],
    entitlements: [
      { commodity: 'Raw Rice (ಅಕ್ಕಿ - Anna Bhagya)', quantity: '20 kg (5 kg / member)', rate: 'Free (₹0.00)', subsidy: '100% Food & Civil Supplies Subsidized' },
      { commodity: 'Fortified Wheat (ಗೋಧಿ)', quantity: '5 kg', rate: '₹2.00 / kg', subsidy: 'Subsidized Central NFSA' },
      { commodity: 'Refined Sugar (ಸಕ್ಕರೆ)', quantity: '1 kg', rate: '₹13.50 / kg', subsidy: 'Subsidized' },
    ],
  },
  // 2. Bengaluru Urban - Shop #105
  {
    id: 'BEN-BLR-002',
    rationCardNumber: 'KA-04-AAY-771920',
    cardType: 'AAY (Antyodaya)',
    headOfHousehold: 'Ningappa Pujari',
    headOfHouseholdKn: 'ನಿಂಗಪ್ಪ ಪೂಜಾರಿ',
    districtId: 'DIST-BLR-URBAN',
    district: 'Bengaluru Urban',
    taluk: 'Bengaluru North',
    ward: 'Ward 42 (Malleshwaram)',
    assignedFpsId: 'KA-BLR-FPS-105',
    assignedFpsName: 'Gayatri Mahila Seva Co-op PDS (Shop #105)',
    assignedFpsAddress: '8th Main, Pipeline Road, Malleshwaram, Bengaluru 560003',
    phoneNumber: '+91 94480 33119',
    totalQuotaKg: 35,
    currentCycleCollected: false,
    activeTokenNumber: 'TKN-2026-09-0771',
    loginPin: '771920',
    aadhaarLast4: '3312',
    members: [
      { name: 'Ningappa Pujari', relation: 'Head', age: 67, gender: 'Male', aadhaarMasked: 'XXXX-XXXX-3312' },
      { name: 'Yellamma Pujari', relation: 'Spouse', age: 62, gender: 'Female', aadhaarMasked: 'XXXX-XXXX-7781' },
      { name: 'Manjula Pujari', relation: 'Daughter', age: 28, gender: 'Female', aadhaarMasked: 'XXXX-XXXX-9021' },
    ],
    entitlements: [
      { commodity: 'Raw Rice (ಅಕ್ಕಿ - AAY Special)', quantity: '28 kg', rate: 'Free (₹0.00)', subsidy: '100% Antyodaya Scheme' },
      { commodity: 'Fortified Wheat (ಗೋಧಿ)', quantity: '7 kg', rate: '₹2.00 / kg', subsidy: 'Subsidized NFSA' },
      { commodity: 'Refined Sugar (ಸಕ್ಕರೆ)', quantity: '1 kg', rate: '₹13.50 / kg', subsidy: 'Subsidized' },
    ],
  },
  // 3. Mysuru - Shop #202
  {
    id: 'BEN-MYS-003',
    rationCardNumber: 'KA-09-PHH-662104',
    cardType: 'PHH (BPL)',
    headOfHousehold: 'Shivanna Gowda',
    headOfHouseholdKn: 'ಶಿವಣ್ಣ ಗೌಡ',
    districtId: 'DIST-MYSURU',
    district: 'Mysuru',
    taluk: 'Mysuru City',
    ward: 'Ward 14 (Saraswathipuram)',
    assignedFpsId: 'KA-MYS-FPS-202',
    assignedFpsName: 'Chamundeshwari Souharda Sahakari PDS (Shop #202)',
    assignedFpsAddress: 'Near 5th Main Bus Stand, Saraswathipuram, Mysuru 570009',
    phoneNumber: '+91 97411 22890',
    totalQuotaKg: 26,
    currentCycleCollected: false,
    activeTokenNumber: 'TKN-2026-09-0662',
    bookedSlot: { date: 'Day 13 (Friday)', timeShift: '10:00 AM - 12:00 PM', bookedAt: '2026-09-22 19:20' },
    loginPin: '662104',
    aadhaarLast4: '1142',
    members: [
      { name: 'Shivanna Gowda', relation: 'Head', age: 52, gender: 'Male', aadhaarMasked: 'XXXX-XXXX-1142' },
      { name: 'Kamalamma Gowda', relation: 'Spouse', age: 48, gender: 'Female', aadhaarMasked: 'XXXX-XXXX-6512' },
      { name: 'Praveen Gowda', relation: 'Son', age: 24, gender: 'Male', aadhaarMasked: 'XXXX-XXXX-4421' },
      { name: 'Rashmi Gowda', relation: 'Daughter', age: 19, gender: 'Female', aadhaarMasked: 'XXXX-XXXX-8902' },
    ],
    entitlements: [
      { commodity: 'Raw Rice (ಅಕ್ಕಿ - Anna Bhagya)', quantity: '20 kg', rate: 'Free (₹0.00)', subsidy: '100% Subsidized' },
      { commodity: 'Fortified Wheat (ಗೋಧಿ)', quantity: '5 kg', rate: '₹2.00 / kg', subsidy: 'Subsidized' },
      { commodity: 'Refined Sugar (ಸಕ್ಕರೆ)', quantity: '1 kg', rate: '₹13.50 / kg', subsidy: 'Subsidized' },
    ],
  },
  // 4. Mysuru - Shop #208
  {
    id: 'BEN-MYS-004',
    rationCardNumber: 'KA-09-PHH-551029',
    cardType: 'PHH (BPL)',
    headOfHousehold: 'Devamma M.',
    headOfHouseholdKn: 'ದೇವಮ್ಮ ಎಂ.',
    districtId: 'DIST-MYSURU',
    district: 'Mysuru',
    taluk: 'Mysuru City',
    ward: 'Ward 08 (Gokulam)',
    assignedFpsId: 'KA-MYS-FPS-208',
    assignedFpsName: 'Kaveri Consumers Co-op Society (Shop #208)',
    assignedFpsAddress: '3rd Stage, 6th Cross, Gokulam, Mysuru 570002',
    phoneNumber: '+91 99802 33418',
    totalQuotaKg: 21,
    currentCycleCollected: true,
    activeTokenNumber: 'TKN-2026-09-0551',
    loginPin: '551029',
    aadhaarLast4: '9081',
    members: [
      { name: 'Devamma M.', relation: 'Head', age: 56, gender: 'Female', aadhaarMasked: 'XXXX-XXXX-9081' },
      { name: 'Siddaraju', relation: 'Son', age: 27, gender: 'Male', aadhaarMasked: 'XXXX-XXXX-3341' },
      { name: 'Geethamma', relation: 'Daughter-in-Law', age: 23, gender: 'Female', aadhaarMasked: 'XXXX-XXXX-7729' },
    ],
    entitlements: [
      { commodity: 'Raw Rice (ಅಕ್ಕಿ)', quantity: '15 kg', rate: 'Free (₹0.00)', subsidy: '100% Anna Bhagya' },
      { commodity: 'Fortified Wheat (ಗೋಧಿ)', quantity: '5 kg', rate: '₹2.00 / kg', subsidy: 'Subsidized' },
      { commodity: 'Refined Sugar (ಸಕ್ಕರೆ)', quantity: '1 kg', rate: '₹13.50 / kg', subsidy: 'Subsidized' },
    ],
  },
  // 5. Belagavi - Shop #305
  {
    id: 'BEN-BEL-005',
    rationCardNumber: 'KA-22-PHH-441982',
    cardType: 'PHH (BPL)',
    headOfHousehold: 'Mallikarjun Chougale',
    headOfHouseholdKn: 'ಮಲ್ಲಿಕಾರ್ಜುನ ಚೌಗಲೆ',
    districtId: 'DIST-BELAGAVI',
    district: 'Belagavi',
    taluk: 'Belagavi City',
    ward: 'Ward 22 (Tilakwadi)',
    assignedFpsId: 'KA-BEL-FPS-305',
    assignedFpsName: 'Rani Chennamma Raitha Seva Kendra (Shop #305)',
    assignedFpsAddress: 'Congress Road, Near 3rd Railway Gate, Tilakwadi, Belagavi 590006',
    phoneNumber: '+91 94498 77120',
    totalQuotaKg: 31,
    currentCycleCollected: false,
    activeTokenNumber: 'TKN-2026-09-0441',
    bookedSlot: { date: 'Day 14 (Saturday)', timeShift: '02:00 PM - 04:00 PM', bookedAt: '2026-09-22 17:15' },
    loginPin: '441982',
    aadhaarLast4: '6621',
    members: [
      { name: 'Mallikarjun Chougale', relation: 'Head', age: 50, gender: 'Male', aadhaarMasked: 'XXXX-XXXX-6621' },
      { name: 'Laxmibai Chougale', relation: 'Spouse', age: 46, gender: 'Female', aadhaarMasked: 'XXXX-XXXX-8812' },
      { name: 'Ravi Chougale', relation: 'Son', age: 22, gender: 'Male', aadhaarMasked: 'XXXX-XXXX-1109' },
      { name: 'Kavita Chougale', relation: 'Daughter', age: 19, gender: 'Female', aadhaarMasked: 'XXXX-XXXX-9943' },
      { name: 'Pooja Chougale', relation: 'Daughter', age: 15, gender: 'Female', aadhaarMasked: 'XXXX-XXXX-5520' },
    ],
    entitlements: [
      { commodity: 'Raw Rice (ಅಕ್ಕಿ - Anna Bhagya)', quantity: '25 kg', rate: 'Free (₹0.00)', subsidy: '100% Subsidized' },
      { commodity: 'Fortified Wheat (ಗೋಧಿ)', quantity: '5 kg', rate: '₹2.00 / kg', subsidy: 'Subsidized' },
      { commodity: 'Refined Sugar (ಸಕ್ಕರೆ)', quantity: '1 kg', rate: '₹13.50 / kg', subsidy: 'Subsidized' },
    ],
  },
  // 6. Belagavi - Shop #312
  {
    id: 'BEN-BEL-006',
    rationCardNumber: 'KA-22-AAY-338102',
    cardType: 'AAY (Antyodaya)',
    headOfHousehold: 'Shanta Kulkarni',
    headOfHouseholdKn: 'ಶಾಂತಾ ಕುಲಕರ್ಣಿ',
    districtId: 'DIST-BELAGAVI',
    district: 'Belagavi',
    taluk: 'Belagavi City',
    ward: 'Ward 10 (Camp)',
    assignedFpsId: 'KA-BEL-FPS-312',
    assignedFpsName: 'Kittur Co-operative Society (Shop #312)',
    assignedFpsAddress: 'Club Road, Camp, Belagavi 590001',
    phoneNumber: '+91 97410 88219',
    totalQuotaKg: 35,
    currentCycleCollected: false,
    activeTokenNumber: 'TKN-2026-09-0338',
    loginPin: '338102',
    aadhaarLast4: '5510',
    members: [
      { name: 'Shanta Kulkarni', relation: 'Head', age: 69, gender: 'Female', aadhaarMasked: 'XXXX-XXXX-5510' },
      { name: 'Gopal Kulkarni', relation: 'Son', age: 38, gender: 'Male', aadhaarMasked: 'XXXX-XXXX-4491' },
      { name: 'Vidya Kulkarni', relation: 'Daughter-in-Law', age: 34, gender: 'Female', aadhaarMasked: 'XXXX-XXXX-8820' },
    ],
    entitlements: [
      { commodity: 'Raw Rice (ಅಕ್ಕಿ - Antyodaya)', quantity: '28 kg', rate: 'Free (₹0.00)', subsidy: '100% Antyodaya' },
      { commodity: 'Fortified Wheat (ಗೋಧಿ)', quantity: '7 kg', rate: '₹2.00 / kg', subsidy: 'Subsidized' },
    ],
  },
  // 7. Kalaburagi - Shop #401
  {
    id: 'BEN-KLB-007',
    rationCardNumber: 'KA-32-PHH-229104',
    cardType: 'PHH (BPL)',
    headOfHousehold: 'Sharanappa Rathod',
    headOfHouseholdKn: 'ಶರಣಪ್ಪ ರಾಥೋಡ್',
    districtId: 'DIST-KALABURAGI',
    district: 'Kalaburagi',
    taluk: 'Kalaburagi City',
    ward: 'Ward 18 (Super Market)',
    assignedFpsId: 'KA-KLB-FPS-401',
    assignedFpsName: 'Sharana Basaveshwara Annapurna Kendra (Shop #401)',
    assignedFpsAddress: 'Main Road, Old City Market, Kalaburagi 585101',
    phoneNumber: '+91 98453 11928',
    totalQuotaKg: 26,
    currentCycleCollected: false,
    activeTokenNumber: 'TKN-2026-09-0229',
    bookedSlot: { date: 'Day 12 (Thursday)', timeShift: '04:00 PM - 06:00 PM', bookedAt: '2026-09-22 16:30' },
    loginPin: '229104',
    aadhaarLast4: '7721',
    members: [
      { name: 'Sharanappa Rathod', relation: 'Head', age: 45, gender: 'Male', aadhaarMasked: 'XXXX-XXXX-7721' },
      { name: 'Seetabai Rathod', relation: 'Spouse', age: 41, gender: 'Female', aadhaarMasked: 'XXXX-XXXX-3301' },
      { name: 'Vijay Rathod', relation: 'Son', age: 19, gender: 'Male', aadhaarMasked: 'XXXX-XXXX-6612' },
      { name: 'Sunita Rathod', relation: 'Daughter', age: 16, gender: 'Female', aadhaarMasked: 'XXXX-XXXX-9904' },
    ],
    entitlements: [
      { commodity: 'Raw Rice (ಅಕ್ಕಿ - Anna Bhagya)', quantity: '20 kg', rate: 'Free (₹0.00)', subsidy: '100% Anna Bhagya' },
      { commodity: 'Fortified Wheat (ಗೋಧಿ)', quantity: '5 kg', rate: '₹2.00 / kg', subsidy: 'Subsidized' },
      { commodity: 'Refined Sugar (ಸಕ್ಕರೆ)', quantity: '1 kg', rate: '₹13.50 / kg', subsidy: 'Subsidized' },
    ],
  },
  // 8. Kalaburagi - Shop #401
  {
    id: 'BEN-KLB-008',
    rationCardNumber: 'KA-32-PHH-118274',
    cardType: 'PHH (BPL)',
    headOfHousehold: 'Fatima Begum',
    headOfHouseholdKn: 'ಫಾತಿಮಾ ಬೇಗಂ',
    districtId: 'DIST-KALABURAGI',
    district: 'Kalaburagi',
    taluk: 'Kalaburagi City',
    ward: 'Ward 24 (MSK Mill)',
    assignedFpsId: 'KA-KLB-FPS-401',
    assignedFpsName: 'Sharana Basaveshwara Annapurna Kendra (Shop #401)',
    assignedFpsAddress: 'Main Road, Old City Market, Kalaburagi 585101',
    phoneNumber: '+91 97412 88192',
    totalQuotaKg: 26,
    currentCycleCollected: false,
    activeTokenNumber: 'TKN-2026-09-0118',
    loginPin: '118274',
    aadhaarLast4: '4410',
    members: [
      { name: 'Fatima Begum', relation: 'Head', age: 52, gender: 'Female', aadhaarMasked: 'XXXX-XXXX-4410' },
      { name: 'Mohammed Iqbal', relation: 'Son', age: 26, gender: 'Male', aadhaarMasked: 'XXXX-XXXX-2291' },
      { name: 'Ayesha Banu', relation: 'Daughter', age: 22, gender: 'Female', aadhaarMasked: 'XXXX-XXXX-8819' },
      { name: 'Zoya Khan', relation: 'Granddaughter', age: 4, gender: 'Female', aadhaarMasked: 'XXXX-XXXX-1120' },
    ],
    entitlements: [
      { commodity: 'Raw Rice (ಅಕ್ಕಿ - Anna Bhagya)', quantity: '20 kg', rate: 'Free (₹0.00)', subsidy: '100% Anna Bhagya' },
      { commodity: 'Fortified Wheat (ಗೋಧಿ)', quantity: '5 kg', rate: '₹2.00 / kg', subsidy: 'Subsidized' },
      { commodity: 'Refined Sugar (ಸಕ್ಕರೆ)', quantity: '1 kg', rate: '₹13.50 / kg', subsidy: 'Subsidized' },
    ],
  },
  // 9. Dakshina Kannada (Mangaluru) - Shop #510
  {
    id: 'BEN-DKN-009',
    rationCardNumber: 'KA-19-PHH-992810',
    cardType: 'PHH (BPL)',
    headOfHousehold: "Prema D'Souza",
    headOfHouseholdKn: 'ಪ್ರೇಮಾ ಡಿಸೋಜಾ',
    districtId: 'DIST-DAKSHINA-KANNADA',
    district: 'Dakshina Kannada',
    taluk: 'Mangaluru',
    ward: 'Ward 32 (Hampankatta)',
    assignedFpsId: 'KA-DKN-FPS-510',
    assignedFpsName: 'Kudroli Gokarnanatha Seva Trust PDS (Shop #510)',
    assignedFpsAddress: 'K.S. Rao Road, Hampankatta, Mangaluru 575001',
    phoneNumber: '+91 98450 77291',
    totalQuotaKg: 21,
    currentCycleCollected: false,
    activeTokenNumber: 'TKN-2026-09-0992',
    loginPin: '992810',
    aadhaarLast4: '8823',
    members: [
      { name: "Prema D'Souza", relation: 'Head', age: 49, gender: 'Female', aadhaarMasked: 'XXXX-XXXX-8823' },
      { name: "Rohan D'Souza", relation: 'Son', age: 23, gender: 'Male', aadhaarMasked: 'XXXX-XXXX-5512' },
      { name: "Sylvia D'Souza", relation: 'Daughter', age: 20, gender: 'Female', aadhaarMasked: 'XXXX-XXXX-9918' },
    ],
    entitlements: [
      { commodity: 'Boiled Rice (ಕುಚಲಕ್ಕಿ - Anna Bhagya)', quantity: '15 kg', rate: 'Free (₹0.00)', subsidy: '100% Anna Bhagya' },
      { commodity: 'Fortified Wheat (ಗೋಧಿ)', quantity: '5 kg', rate: '₹2.00 / kg', subsidy: 'Subsidized' },
      { commodity: 'Refined Sugar (ಸಕ್ಕರೆ)', quantity: '1 kg', rate: '₹13.50 / kg', subsidy: 'Subsidized' },
    ],
  },
  // 10. Dakshina Kannada (Mangaluru) - Shop #510
  {
    id: 'BEN-DKN-010',
    rationCardNumber: 'KA-19-AAY-883719',
    cardType: 'AAY (Antyodaya)',
    headOfHousehold: 'Sanjeeva Poojary',
    headOfHouseholdKn: 'ಸಂಜೀವ ಪೂಜಾರಿ',
    districtId: 'DIST-DAKSHINA-KANNADA',
    district: 'Dakshina Kannada',
    taluk: 'Mangaluru',
    ward: 'Ward 28 (Urwa)',
    assignedFpsId: 'KA-DKN-FPS-510',
    assignedFpsName: 'Kudroli Gokarnanatha Seva Trust PDS (Shop #510)',
    assignedFpsAddress: 'K.S. Rao Road, Hampankatta, Mangaluru 575001',
    phoneNumber: '+91 94481 99023',
    totalQuotaKg: 35,
    currentCycleCollected: false,
    activeTokenNumber: 'TKN-2026-09-0883',
    bookedSlot: { date: 'Day 13 (Friday)', timeShift: '08:00 AM - 10:00 AM', bookedAt: '2026-09-22 15:40' },
    loginPin: '883719',
    aadhaarLast4: '9902',
    members: [
      { name: 'Sanjeeva Poojary', relation: 'Head', age: 71, gender: 'Male', aadhaarMasked: 'XXXX-XXXX-9902' },
      { name: 'Janaki Poojary', relation: 'Spouse', age: 66, gender: 'Female', aadhaarMasked: 'XXXX-XXXX-3349' },
      { name: 'Mohan Poojary', relation: 'Son', age: 39, gender: 'Male', aadhaarMasked: 'XXXX-XXXX-7721' },
    ],
    entitlements: [
      { commodity: 'Boiled Rice (ಕುಚಲಕ್ಕಿ - AAY Special)', quantity: '28 kg', rate: 'Free (₹0.00)', subsidy: '100% Antyodaya' },
      { commodity: 'Fortified Wheat (ಗೋಧಿ)', quantity: '7 kg', rate: '₹2.00 / kg', subsidy: 'Subsidized NFSA' },
    ],
  },
];
